# TP1

In [ ]:
    import numpy as np
    import pandas as pd
    import matplotlib.pyplot as plt

In [88]:
# 2. Chargement des donnees
data = pd.read_csv('data/USA_Housing.csv')

In [89]:
data.head()

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   
4      59982.197226             5.040555                   7.839388   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   
4                          4.23     26354.109472  6.309435e+05   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820  
4                         USNS Raymond\nFPO AE 09386

In [90]:
donnees_maison = pd.read_csv('data/USA_Housing.csv')

In [91]:
donnees_maison

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0         79545.458574             5.682861                   7.009188   
1         79248.642455             6.002900                   6.730821   
2         61287.067179             5.865890                   8.512727   
3         63345.240046             7.188236                   5.586729   
4         59982.197226             5.040555                   7.839388   
...                ...                  ...                        ...   
4995      60567.944140             7.830362                   6.137356   
4996      78491.275435             6.999135                   6.576763   
4997      63390.686886             7.250591                   4.805081   
4998      68001.331235             5.534388                   7.130144   
4999      65510.581804             5.992305                   6.792336   

      Avg. Area Number of Bedrooms  Area Population         Price  \
0                             4.09     23086.800503  1.059034e+06   
1                             3.09     40173.072174  1.505891e+06   
2                             5.13     36882.159400  1.058988e+06   
3                             3.26     34310.242831  1.260617e+06   
4                             4.23     26354.109472  6.309435e+05   
...                            ...              ...           ...   
4995                          3.46     22837.361035  1.060194e+06   
4996                          4.02     25616.115489  1.482618e+06   
4997                          2.13     33266.145490  1.030730e+06   
4998                          5.44     42625.620156  1.198657e+06   
4999                          4.07     46501.283803  1.298950e+06   

                                                Address  
0     208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1     188 Johnson Views Suite 079\nLake Kathleen, CA...  
2     9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                             USS Barnett\nFPO AP 44820  
4                            USNS Raymond\nFPO AE 09386  
...                                                 ...  
4995                   USNS Williams\nFPO AP 30153-7653  
4996              PSC 9258, Box 8489\nAPO AA 42991-3352  
4997  4215 Tracy Garden Suite 076\nJoshualand, VA 01...  
4998                          USS Wallace\nFPO AE 73316  
4999  37778 George Ridges Apt. 509\nEast Holly, NV 2...  

[5000 rows x 7 columns]

In [92]:
donnees_maison.head(4)

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820

In [93]:
donnees_maison[['Avg. Area Income', 'Price']]

Avg. Area Income         Price
0         79545.458574  1.059034e+06
1         79248.642455  1.505891e+06
2         61287.067179  1.058988e+06
3         63345.240046  1.260617e+06
4         59982.197226  6.309435e+05
...                ...           ...
4995      60567.944140  1.060194e+06
4996      78491.275435  1.482618e+06
4997      63390.686886  1.030730e+06
4998      68001.331235  1.198657e+06
4999      65510.581804  1.298950e+06

[5000 rows x 2 columns]

In [94]:
donnees_maison['Avg. Area Income'].max()

np.float64(107701.74837763936)

In [95]:
donnees_maison['Avg. Area Income'].min()

np.float64(17796.631189543397)

In [96]:
donnees_maison.head(4)

Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0      79545.458574             5.682861                   7.009188   
1      79248.642455             6.002900                   6.730821   
2      61287.067179             5.865890                   8.512727   
3      63345.240046             7.188236                   5.586729   

   Avg. Area Number of Bedrooms  Area Population         Price  \
0                          4.09     23086.800503  1.059034e+06   
1                          3.09     40173.072174  1.505891e+06   
2                          5.13     36882.159400  1.058988e+06   
3                          3.26     34310.242831  1.260617e+06   

                                             Address  
0  208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1  188 Johnson Views Suite 079\nLake Kathleen, CA...  
2  9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                          USS Barnett\nFPO AP 44820

In [97]:
x = donnees_maison.iloc[ : , :1].values
y = donnees_maison.iloc[ : , -2].values


x

In [98]:
y

array([1059033.55787012, 1505890.91484695, 1058987.98787608, ...,
       1030729.58315229, 1198656.87240769, 1298950.48026696],
      shape=(5000,))

# 1 Separation de donnees : Train et Test

In [99]:
#x_train, x_test, y_train, y_test
from sklearn.model_selection import train_test_split

In [100]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 40)

In [101]:
print("x-train Shape :", x_train.shape)
print("x-test Shape :", x_test.shape)
print("y-train Shape :", y_train.shape)
print("y-test Shape :", y_test.shape)

x-train Shape : (3750, 1)
x-test Shape : (1250, 1)
y-train Shape : (3750,)
y-test Shape : (1250,)


# 2. Construire le Modele

In [102]:
from sklearn.linear_model import LinearRegression

In [103]:
modele_lineaire = LinearRegression()

In [104]:
modele_lineaire.fit(x_train, y_train)

LinearRegression()

In [105]:
y_price_predits = modele_lineaire.predict(x_test)

In [106]:
y_price_predits

array([1375827.6030198 , 1594792.46082882, 1378886.12389639, ...,
       1092889.80072731, 1437100.12333213, 1386649.52532991],
      shape=(1250,))

In [107]:
y_test

array([1435769.76883739, 1668448.09805727, 1762214.67958189, ...,
        975005.77366035, 1393995.96182827, 1036277.0624633 ],
      shape=(1250,))

In [108]:
resulats = pd.DataFrame(y_test , y_price_predits)

In [109]:
from sklearn.metrics import mean_squared_error, r2_score

In [110]:
print("MSE de la Regression Lineaire :", mean_squared_error(y_test, y_price_predits))

MSE de la Regression Lineaire : 70345556190.3212


In [111]:
print("r2_score de la Regression Lineaire :", r2_score(y_test, y_price_predits))

r2_score de la Regression Lineaire : 0.43322233931263276


# 3. Visualisation des résultats

In [ ]:
plt.scatter(x_train, y_train, color='red', label='Train Data')
plt.scatter(x_test, y_test, color='blue', label='Data Test')
plt.plot(x_train, modele_lineaire.predict(x_train), color='yellow', label='Ligne de Regression')
plt.xlabel('Revenus')
plt.ylabel('Prix')
plt.title('Regression Lineaire Simple')
plt.legend()
plt.show()

# 4.Pediction simple

In [119]:
resulats = pd.DataFrame({'y-prix-reels': y_test, 'y_prix_predits' :y_price_predits})
resulats

y-prix-reels  y_prix_predits
0     1.435770e+06    1.375828e+06
1     1.668448e+06    1.594792e+06
2     1.762215e+06    1.378886e+06
3     1.106261e+06    1.121330e+06
4     1.051124e+06    1.001248e+06
...            ...             ...
1245  7.054441e+05    9.409852e+05
1246  1.358647e+06    1.629427e+06
1247  9.750058e+05    1.092890e+06
1248  1.393996e+06    1.437100e+06
1249  1.036277e+06    1.386650e+06

[1250 rows x 2 columns]

In [120]:
y_price_predits

array([1375827.6030198 , 1594792.46082882, 1378886.12389639, ...,
       1092889.80072731, 1437100.12333213, 1386649.52532991],
      shape=(1250,))

In [121]:
y

array([1059033.55787012, 1505890.91484695, 1058987.98787608, ...,
       1030729.58315229, 1198656.87240769, 1298950.48026696],
      shape=(5000,))

In [122]:
print(modele_lineaire.predict([[2.5]]))

[-202264.54106697]


In [123]:
print(modele_lineaire.predict([[10]]))

[-202107.54651146]


In [118]:
resulats = pd.DataFrame({'y-prix-reels': y_test, 'y_prix_predits' :y_price_predits})
resulats['Difference'] = resulats['y-prix-reels'] - resulats['y_prix_predits']
resulats

y-prix-reels  y_prix_predits     Difference
0     1.435770e+06    1.375828e+06   59942.165818
1     1.668448e+06    1.594792e+06   73655.637228
2     1.762215e+06    1.378886e+06  383328.555685
3     1.106261e+06    1.121330e+06  -15068.763964
4     1.051124e+06    1.001248e+06   49875.895328
...            ...             ...            ...
1245  7.054441e+05    9.409852e+05 -235541.106927
1246  1.358647e+06    1.629427e+06 -270780.446581
1247  9.750058e+05    1.092890e+06 -117884.027067
1248  1.393996e+06    1.437100e+06  -43104.161504
1249  1.036277e+06    1.386650e+06 -350372.462867

[1250 rows x 3 columns]

In [126]:
print(modele_lineaire.predict([[61287.067178656784]]))

[1080581.24347811]
